@startuml

actor "Vendor" as V
actor "Admin" as A
actor "Customer" as U

participant "Menu Srv" as M

A -> M: Add/Edit/Remove/Disable items in Menu
V -> M: Add/Edit/Remove/Disable items in Menu
U -> M : View/Search Menu
@enduml
