@startuml

actor "Admin" as A
actor "Vendor" as V
actor "Kitchen" as K
actor "Customer" as U

participant "Vendor Srv" as Vsrv


A -> Vsrv: Add/Edit/Remove/Disable Vendors
V -> Vsrv: Partial Edit/View its profile
K -> Vsrv: View public vendor profile
U -> Vsrv: View public vendor profile
@enduml
